//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.ArticleTag = new HashSet<ArticleTag>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int PostId { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual ICollection<ArticleTag> ArticleTag { get; set; }
    }
}
