//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Post = new HashSet<Post>();
            this.UserRole = new HashSet<UserRole>();
            this.Mark = new HashSet<Mark>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public string AvatarUrl { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Post> Post { get; set; }
        public virtual ICollection<UserRole> UserRole { get; set; }
        public virtual ICollection<Mark> Mark { get; set; }
    }
}
